#!/bin/bash

# Read fields from JSON
name=$(jq -r '.name' data.json | sed 's/.*/\u&/') # Capitalize first letter
height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1 / 10}') # convert decimetres to metres
weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1 / 10}') # convert hectograms to kg
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/') # Capitalize

# Output in human-readable format
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
